### ISSUE TITLE
matcaffe error

### ISSUE THREAD

**Issue by kli-casia** [wanglimin/TDD#1]
Hi, LiMin
When I run script_demo.m

```
>> script_demo
Extract improved trajectories...
video size, length: 55, width: 320, height: 240
Extract TVL1 optical flow field...
Extract spatial TDD...
Undefined function 'caffe' for input arguments of type 'char'.

Error in RGBCNNFeature (line 18)
if caffe('is_initialized') == 0

Error in script_demo (line 32)
feature_conv = RGBCNNFeature(vid_name, 1, sizes_vid(scale,1), sizes_vid(scale,2), model_def_file, model_file, gpu_id);

```

what's wrong? I am using the latest version of caffe.
Thank you very much!

**Comment by wanglimin** [comment]
Undefined function 'caffe' for input arguments of type 'char'.

It indicates that your matlab cannot find your matcaffe function.

BTW, our code is compatible with previous caffe version, but not with
latest version.

Limin

**Comment by kli-casia** [comment]
Hi,LiMin
I use an old version of caffe,but.....

```
I0721 22:01:42.451390  7971 net.cpp:175] Memory required for Data 884736000
Done with init
Using GPU Mode
Done with set_mode
Done with set_phase_test
Extract temporal TDD...
I0721 22:01:44.132243  7971 matcaffe.cpp:286] Network reset, call init before use it again
Error using matcaffe_init (line 22)
You need a network model file

Error in FlowCNNFeature (line 27)
                matcaffe_init(use_gpu,model_def_file,model_file,gpu_id);

Error in script_demo (line 53)
feature_conv = FlowCNNFeature('test/', 1, sizes_vid(scale,1), sizes_vid(scale,2),model_def_file, model_file,
gpu_id);
```

**Comment by wanglimin** [comment]
You should put spatial.caffemodel in your current directory. It indicates
your code cannot find the network model file.

Limin

**Comment by wanglimin** [comment]
Sorry, it should be "temporal.caffemodel".

**Comment by kli-casia** [comment]
BTW, there is a tiny error in the code.
I change

```
system(['./dense_flow -f ',vid_name,' -x test/flow_x -y test/flow_y -b 20 -t 1 -d 3']);
```

to

```
system(['./dense_flow -f ',vid_name,' -x test/flow_x_ -y test/flow_y_ -b 20 -t 1 -d 3']);
```

in line 12 of script_demo.m

and change

```
flow_x = imread(sprintf('%s_%04d.jpg',[vid_name,'flow_x'],i));
flow_y = imread(sprintf('%s_%04d.jpg',[vid_name,'flow_y'],i));

```

to

```
flow_x = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_x'],i));
flow_y = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_y'],i));
```

in line 13 of FlowCNNFeature.m

Because I find the output of dense_flow binary don't match `imread(sprintf('%s_%04d.jpg',[vid_name,'flow_x'],i));`

**Comment by kli-casia** [comment]
Hi, LiMin
I put temporal.caffemodel file in current directory, but...........

```
Unable to read file 'flow_mean': no such file or directory.

Error in FlowCNNFeature (line 35)
d  = load('flow_mean');
```

Where can I download the mean file?
Thank you very much.

**Comment by wanglimin** [comment]
I will upload the 'flow_mean.mat' file. 

I cannot figure out why you change code into 

system(['./dense_flow -f ',vid_name,' -x test/flow_x_ -y test/flow_y_ -b 20 -t 1 -d 3']);

For our latest dense_flow code, our output is:

sprintf(tmp,"_%04d.jpg",int(frame_num));

So the FlowCNNFeature.m should be OK.

**Comment by kli-casia** [comment]
oh, I see. perhas I use an older version of your dense_flow code. Thank you very much.

**Comment by wanglimin** [comment]
The file of "flow_mean.mat" has been uploaded.

**Comment by kli-casia** [comment]
Great, I will try it out!

**Comment by kli-casia** [comment]
Cheers! Everything works fine!
Thank you very much, LiMin

**Comment by venu9** [comment]
Hi LiMin,

While running the script script_demo.m, I'm getting the following error Even though the search path of the MATLAB is set to matcaffe.

Undefined function 'caffe' for input arguments of type 'char'.
Error in RGBCNNFeature (line 25)
if caffe('is_initialized') == 0
Error in script_demo (line 32)
feature_conv = RGBCNNFeature(vid_name, 1, sizes_vid(scale,1), sizes_vid(scale,2), model_def_file, model_file, gpu_id);

What could be the problem ?
Thanks.

**Comment by wanglimin** [comment]
It indicates could not find the caffe function or your caffe function may
be the new version, which is not compatible with char input.

Best,

Limin

On Tue, Aug 4, 2015 at 2:18 PM, venu9 notifications@github.com wrote:

> Hi LiMin,
> 
> While running the script script_demo.m, I'm getting the following error
> Even though the search path of the MATLAB is set to matcaffe.
> 
> Undefined function 'caffe' for input arguments of type 'char'.
> Error in RGBCNNFeature (line 25)
> if caffe('is_initialized') == 0
> Error in script_demo (line 32)
> feature_conv = RGBCNNFeature(vid_name, 1, sizes_vid(scale,1),
> sizes_vid(scale,2), model_def_file, model_file, gpu_id);
> 
> What could be the problem ?
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanglimin/TDD/issues/1#issuecomment-127491551.

## 

Limin Wang
PhD, The Chinese University of Hong Kong
Homepage: http://wanglimin.github.io/
