### ISSUE TITLE
Different features  for the same video  in matlab and VS2013.

### ISSUE THREAD

**Issue by Mark1880** [wanglimin/TDD#10]
Hello @wanglimin 
I have download your modified iDT feature code and compiled it in the release mode by myself in VS2013 win10, then I have the .exe file .
I can not understand why Some videos  in 'hmdb51_sta.'  have different  number of trajectories and features  in Matlab   using the command system(['./DenseTrackStab -f ',vid_name,' -o ',vid_name(1:end-4),'.bin'])   compared with  running the code in vs12013.

Thanks,
Mark

**Comment by wanglimin** [comment]
@Mark1880 I think it may depend on the decoding package you used. In you case, you need to check wether you use the same decoding package for different vs.

**Comment by Mark1880** [comment]
Thanks  @wanglimin 
I think as you  said because i have two  opencv versions in my PC .
Thanks, 
Mark
