### ISSUE TITLE
script_demo.m problem

### ISSUE THREAD

**Issue by kli-casia** [wanglimin/TDD#2]
Hi, LiMin.
What's the meaning of sizes in line 19 of script_demo

```
sizes = [8,8; 11.4286,11.4286; 16,16; 22.8571,24;32,34.2587];%why?
```

In my opinion, according to your paper, sizes shold be

```
 [16*1/2,16*1/2; 16*1/sqrt(2), 16*1/sqrt(2); 16,16;16*sqrt(2),16*sqrt(2);16*2,16*2]
```

Am I misunderstanding something?

**Comment by wanglimin** [comment]
You are right. As the convolutional map size must be integer, the map size
ratio will not be the exact value in theory.

On Wed, Jul 22, 2015 at 7:05 PM, Kai Li notifications@github.com wrote:

> Hi, LiMin.
> What's the meaning of sizes in line 19 of script_demo
> 
> sizes = [8,8; 11.4286,11.4286; 16,16; 22.8571,24;32,34.2587];%why?
> 
> In my opinion, according to your paper, sizes shold be
> 
>  [16_1/2,16_1/2; 16_1/sqrt(2), 16_1/sqrt(2); 16,16;16_sqrt(2),16_sqrt(2);16_2,16_2]
> 
> Am I misunderstanding something?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanglimin/TDD/issues/2.

## 

WANG Limin
Postgraduate of Department of Information Engineering, CUHK, Hong Kong.
Undergraduate of Department of Computer Science and Technology, NJU, China.

**Comment by kli-casia** [comment]
Thank you very much, I understand it.
