### ISSUE TITLE
FlowCNNFeature.m

### ISSUE THREAD

**Issue by kli-casia** [wanglimin/TDD#3]
Hi, LiMin
The code in FlowCNNFeature.m

```
function FCNNFeature = FlowCNNFeature(vid_name, use_gpu, NUM_HEIGHT, NUM_WIDTH, model_def_file, model_file, gpu_id)
L = 10;
% Input video
filelist =dir([vid_name,'*_x*.jpg']);
if length(filelist) > 30 *60
    video = zeros(NUM_HEIGHT,NUM_WIDTH,L*2,30*60,'single');
else
    video = zeros(NUM_HEIGHT,NUM_WIDTH,L*2,length(filelist),'single');
end

for i = 1:size(video,4)
    flow_x = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_x'],i));
    flow_y = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_y'],i));
    video(:,:,1,i) = imresize(flow_x,[NUM_HEIGHT,NUM_WIDTH],'bilinear');
    video(:,:,2,i) = imresize(flow_y,[NUM_HEIGHT,NUM_WIDTH],'bilinear');
end

for i = 1:L-1% 
    tmp = cat(4, video(:,:,(i-1)*2+1:i*2,2:end),video(:,:,(i-1)*2+1:i*2,end));%240*320*2*54
    video(:,:,i*2+1:i*2+2,:)  = tmp;
end
```

**I find it hard to understand the code** 

```
for i = 1:L-1% 
    tmp = cat(4, video(:,:,(i-1)*2+1:i*2,2:end),video(:,:,(i-1)*2+1:i*2,end));%
    video(:,:,i*2+1:i*2+2,:)  = tmp;
end
```

For example there are 55 frames in a video, so the variable **video**'s shape is (240 320 20 55).
For every frame, there are 20 flow images with size 240*320 corresponds to it.
According to the code, for every frame, the first two flow image are flow_x and flow_y, the remaining 18 flow images are just the copy of the first two?
Does this make sense? 

Why not just use

```
 tmp =video(:,:,(i-1)*2+1:i*2,1:end);
```

**Comment by wanglimin** [comment]
You can try some other smarter method such as interpolation.

On Wed, Jul 22, 2015 at 9:07 PM, Kai Li notifications@github.com wrote:

> Hi, LiMin
> The code in FlowCNNFeature.m
> 
> function FCNNFeature = FlowCNNFeature(vid_name, use_gpu, NUM_HEIGHT, NUM_WIDTH, model_def_file, model_file, gpu_id)
> L = 10;
> % Input video
> filelist =dir([vid_name,'__x_.jpg']);
> if length(filelist) > 30 _60
>     video = zeros(NUM_HEIGHT,NUM_WIDTH,L_2,30_60,'single');
> else
>     video = zeros(NUM_HEIGHT,NUM_WIDTH,L_2,length(filelist),'single');
> end
> 
> for i = 1:size(video,4)
>     flow_x = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_x'],i));
>     flow_y = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_y'],i));
>     video(:,:,1,i) = imresize(flow_x,[NUM_HEIGHT,NUM_WIDTH],'bilinear');
>     video(:,:,2,i) = imresize(flow_y,[NUM_HEIGHT,NUM_WIDTH],'bilinear');
> end
> 
> for i = 1:L-1%
>     tmp = cat(4, video(:,:,(i-1)_2+1:i_2,2:end),video(:,:,(i-1)_2+1:i_2,end));%240_320_2_54
>     video(:,:,i_2+1:i*2+2,:)  = tmp;
> end
> 
> _I find it hard to understand the code_
> 
> for i = 1:L-1%
>     tmp = cat(4, video(:,:,(i-1)_2+1:i_2,2:end),video(:,:,(i-1)_2+1:i_2,end));%
>     video(:,:,i_2+1:i_2+2,:)  = tmp;
> end
> 
> For example there are 55 frames in a video, so the variable _video_'s
> shape is (240_320_20
> _55). For every frame, there are 20 flow images with size 240_320
> corresponds to it.
> According to the code, for every frame, the first two flow image are
> flow_x and flow_y, the remaining 18 flow images are just the copy of the
> first two?
> Does this make sense?
> 
> Why not just use
> 
>  tmp =video(:,:,(i-1)_2+1:i_2,1:end);
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanglimin/TDD/issues/3.

## 

WANG Limin
Postgraduate of Department of Information Engineering, CUHK, Hong Kong.
Undergraduate of Department of Computer Science and Technology, NJU, China.

**Comment by kli-casia** [comment]
I see, I pay too much attention to details.
Thank you very much, LiMin. I am newbie at deep learning, I learn a lot from your paper and code.

**Comment by wanglimin** [comment]
According to the code, for every frame, the first two flow image are flow_x
and flow_y, the remaining 18 flow images are just the copy of the first two?

Your understanding is wrong. To make sure the temporal duration of
convolutional feature map is equal to the duration of video. So we pad the
(L-1) frame optical flow field at the end.

You can try some other smarter method such as interpolation.

On Wed, Jul 22, 2015 at 9:09 PM, WANG Limin lmwang.nju@gmail.com wrote:

> You can try some other smarter method such as interpolation.
> 
> On Wed, Jul 22, 2015 at 9:07 PM, Kai Li notifications@github.com wrote:
> 
> > Hi, LiMin
> > The code in FlowCNNFeature.m
> > 
> > function FCNNFeature = FlowCNNFeature(vid_name, use_gpu, NUM_HEIGHT, NUM_WIDTH, model_def_file, model_file, gpu_id)
> > L = 10;
> > % Input video
> > filelist =dir([vid_name,'__x_.jpg']);
> > if length(filelist) > 30 _60
> >     video = zeros(NUM_HEIGHT,NUM_WIDTH,L_2,30_60,'single');
> > else
> >     video = zeros(NUM_HEIGHT,NUM_WIDTH,L_2,length(filelist),'single');
> > end
> > 
> > for i = 1:size(video,4)
> >     flow_x = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_x'],i));
> >     flow_y = imread(sprintf('%s_%06d.jpg',[vid_name,'flow_y'],i));
> >     video(:,:,1,i) = imresize(flow_x,[NUM_HEIGHT,NUM_WIDTH],'bilinear');
> >     video(:,:,2,i) = imresize(flow_y,[NUM_HEIGHT,NUM_WIDTH],'bilinear');
> > end
> > 
> > for i = 1:L-1%
> >     tmp = cat(4, video(:,:,(i-1)_2+1:i_2,2:end),video(:,:,(i-1)_2+1:i_2,end));%240_320_2_54
> >     video(:,:,i_2+1:i*2+2,:)  = tmp;
> > end
> > 
> > _I find it hard to understand the code_
> > 
> > for i = 1:L-1%
> >     tmp = cat(4, video(:,:,(i-1)_2+1:i_2,2:end),video(:,:,(i-1)_2+1:i_2,end));%
> >     video(:,:,i_2+1:i_2+2,:)  = tmp;
> > end
> > 
> > For example there are 55 frames in a video, so the variable _video_'s
> > shape is (240_320_20
> > _55). For every frame, there are 20 flow images with size 240_320
> > corresponds to it.
> > According to the code, for every frame, the first two flow image are
> > flow_x and flow_y, the remaining 18 flow images are just the copy of the
> > first two?
> > Does this make sense?
> > 
> > Why not just use
> > 
> >  tmp =video(:,:,(i-1)_2+1:i_2,1:end);
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/wanglimin/TDD/issues/3.
> 
> ## 
> 
> WANG Limin
> Postgraduate of Department of Information Engineering, CUHK, Hong Kong.
> Undergraduate of Department of Computer Science and Technology, NJU, China.

## 

WANG Limin
Postgraduate of Department of Information Engineering, CUHK, Hong Kong.
Undergraduate of Department of Computer Science and Technology, NJU, China.
