### ISSUE TITLE
flow_mean.mat all zero?

### ISSUE THREAD

**Issue by whjxnyzh123** [wanglimin/TDD#4]
The elements of flow_mean.mat  are all zeros?

**Comment by wanglimin** [comment]
Sorry, the mean value should be 128. I have re-uploaded the "flow_mean.mat".

Limin

On Wed, Jul 29, 2015 at 8:52 AM, whjxnyzh notifications@github.com wrote:

> The elements of flow_mean.mat are all zeros?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanglimin/TDD/issues/4.

## 

Limin Wang
PhD, The Chinese University of Hong Kong.
Homepage: http://wanglimin.github.io/
