### ISSUE TITLE
 The value of the input named 'power' of extract_fv.m

### ISSUE THREAD

**Issue by jerryl777** [wanglimin/TDD#5]
Hi, @wanglimin 
I want to reproduce the experiment result in the paper.

And I found a parameter named 'power' in extract_fv.m. The use of this para is setting feature to feature.^power before coding.

What's the value of this para should I set in order to reproduce the result?

Thanks.

**Comment by wanglimin** [comment]
Hi, @cenjiepeng 

In our experiment, we set the value of power as 0.5.

Limin

**Comment by jerryl777** [comment]
Thank you.
So I also need to do the some implement to the raw TDD features(before PCA) in GMM training?

**Comment by wanglimin** [comment]
@cenjiepeng 

Yes, you need to learn GMM by yourself. In our implementation, we use the vl-feat toolbox for GMM training and Fisher vector encoding.

Limin

**Comment by wanglimin** [comment]
@cenjiepeng 

It should be noted that the GMM learning and Fisher vector encoding are based on TDD features after PCA.

Limin

**Comment by jerryl777** [comment]
I get it. Thanks @wanglimin .
