### ISSUE TITLE
Unbalanced category accuracy in HMDB51

### ISSUE THREAD

**Issue by felixpun** [wanglimin/TDD#7]
Hi, @wanglimin 

Have you encountered the problem of unbalanced category accuracy while training and testing on HMDB51 dataset?   For example, the accuracy of the class "kick" is much better than the class "brush_hair" in HMDB51 dataset while testing.

Thanks, 
Philip

**Comment by wanglimin** [comment]
I did not check the per-class accuracy on the HMDB51 dataset.

Limin

**Comment by felixpun** [comment]
@wanglimin 

Thanks for your kind reply.

Philip
