### ISSUE TITLE
spatial_cls.prototxt

### ISSUE THREAD

**Issue by double-vane** [wanglimin/TDD#8]
![image](https://cloud.githubusercontent.com/assets/20334378/18821511/84a4bce8-83d9-11e6-93f0-a29bd6abed3f.png)
这里pad不应该是2？
# _The second modification is that before each convolutional

or pooling layer, with kernel size k, we conduct
zero padding of the layer’s input with size ⌊k/2⌋._  
来自Action Recognition with Trajectory-Pooled Deep-Convolutional Descriptors
可能是我理解有误，还有这个.caffemodel下载不下来啊，需要翻墙吗？
谢谢大神

**Comment by wanglimin** [comment]
This spatial_cls.prototxt is for original classification task not for TDD extraction. For tdd extraction, please refer to following:

https://github.com/wanglimin/TDD/blob/cudnn2.0/model_proto/spatial_net_scale_3.prototxt#L54

Concerning the classification  model, our server is not stable and you may try multiple times.

**Comment by double-vane** [comment]
Thank you for your detailed answer！
