### ISSUE TITLE
 classification issue

### ISSUE THREAD

**Issue by raymondsa** [wanglimin/TDD#9]
Hi @wanglimin 

1)  For each video , the  final dim of features is 262144 (4 \* 65536), am i right?(after concatenating all layers' features ) 
So, the dim for the training file in HMDB51 is  3570 \* 262144,
     the dim for the testing file in HMDB51 is   1530 \*  262144 .Am i right ? .
You mentioned in your paper  "then use a linear SVM as the classifer (C = 100)"
It consumes a lot of time to train a file with  3570*262144  using libsvm library ,am i right  ?
2) You mentioned  "combining TDDs with iDTs, using early fusion of Fisher vector representation"
How do you make the "early fusion" please ?

Thanks 
Raymond

**Comment by wanglimin** [comment]
@raymondsa 

Hi, for your first question, I used the kernel version (K=XX^t) of libsvm to speed up svm training.

For your second question, by "early fusion" I mean first concatenate their fisher vector and then train a svm.

**Comment by raymondsa** [comment]
I see , many thanks @wanglimin 
Thanks
Raymond
